//
// automatically generated by spin2cpp v1.06 on Thu Mar 26 03:46:33 2015
// spin2cpp BALAPILLER.spin 
//

#ifndef SynthSpin_Class_Defined__
#define SynthSpin_Class_Defined__

#include <stdint.h>

class SynthSpin {
public:
  int32_t	Synth(int32_t Ctr_ab, int32_t Pin, int32_t Freq);
  int32_t	Silence_a(int32_t Pin);
  int32_t	Silence_b(int32_t Pin);
private:
  int32_t	Fraction(int32_t A, int32_t B, int32_t Shift);
};

#endif
